name: flutter_bloc_firebase_login_starter
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: 3.2.6
  flutter: 3.16.9

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: 8.1.3
  equatable: 2.0.5
  firebase_core: 2.27.0
  flow_builder: 0.0.10
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.4
  font_awesome_flutter: 10.7.0
  form_inputs:
    path: packages/form_inputs
  formz: 0.7.0
  google_fonts: 6.0.0
  meta: 1.10.0

dev_dependencies:
  flutter_lints: 3.0.1

flutter:
  uses-material-design: true
  assets:
  - assets/